### ISSUE TITLE
What UX tool/component/crate is used to span TUI and GUI (if any)?

### ISSUE THREAD

**Issue by johnnyutahh** [MohamedSherifNoureldin/PCtrl#2]
What UX tool/component/crate is used to span TUI and GUI (if any)?

For example: https://dioxuslabs.com

(I'm too lazy to look through the code to analyze on my own, so I hope you don't mind my lazy question... 🤓)

**Comment by MohamedSherifNoureldin** [comment]
For the TUI we are using [cursive-rs](https://docs.rs/cursive/latest/cursive/) crate with the third-party view [cursive_tree_view](https://github.com/BonsaiDen/cursive_table_view).
For the GUI we are using [Tauri](https://tauri.app/) and the frontend is built using [React](https://react.dev/)
