### ISSUE TITLE
GUI - graphs - displays 14 decimal places 

### ISSUE THREAD

**Issue by Not-Sure-Whats-Going-On** [MohamedSherifNoureldin/PCtrl#6]
When using the GUI option, the numbers displayed on the "System Information & Graphs" tab for CPU and Memory are shown with 14 decimal places - see attached.  The extra digits are meaningless and the numbers should be shown to either 1 decimal place, or rounded to the nearest integer.
![PCtrl-14dp](https://github.com/MohamedSherifNoureldin/PCtrl/assets/93087918/f10f407f-afeb-4cf0-8be1-b8bfeeb26082)

**Comment by MohamedSherifNoureldin** [comment]
I have just pushed a fix to this setting the decimal points of the Pie chart to only 2 decimal places. Thank you for the notice.

**Comment by Not-Sure-Whats-Going-On** [comment]
Thanks Mohamed.  Keep up the good work!
